### ISSUE TITLE
Boxes around blocks when using group block.

### ISSUE THREAD

**Issue by nickhamze** [sortabrilliant/blockshots#2]
Boxes around blocks when using group block.

![core-group-screenshot (3)](https://user-images.githubusercontent.com/158918/73017898-28881200-3de6-11ea-9ca2-862daf1a2333.png)

**Comment by Mamaduka** [comment]
@nickhamze replace `html2canvas` with `dom-to-image-more`. Please test and let me know if you want to keep this library or revert to `html2canvas`.

**Comment by nickhamze** [comment]
We still have the boxes but at least I know what is causing them now. It's this line of CSS:
<img width="324" alt="Screen Shot 2020-01-24 at 6 12 00 AM" src="https://user-images.githubusercontent.com/158918/73068701-78f88180-3e71-11ea-8fa3-c907619d45d1.png">

Is there anyway to pass through a border:0px; on this element via dom to image more. I think it says we can do this but I'm not sure.

```
style
An object whose properties to be copied to node's style before rendering. You might want to check this reference for JavaScript names of CSS properties.
```

**Comment by Mamaduka** [comment]
@nickhamze can you share the "Block Shot"?

**Comment by nickhamze** [comment]
![core-group-screenshot (1)](https://user-images.githubusercontent.com/158918/73073622-50768480-3e7d-11ea-959f-3f3cbd32da1f.png)

**Comment by Mamaduka** [comment]
Based on the source code `style` option if for adding extra styles. I don't think we can use that for our case.

**Comment by nickhamze** [comment]
Hmm, I hate going back and forth but HTML2canvas provided better screenshots IMO.

I found this line of CSS and I think I found the real culprit with html2canvas

```
.block-editor-block-list__layout .block-editor-block-list__block.has-child-selected>.block-editor-block-list__block-edit:before {
    border: 1px dashed rgba(123,134,162,.3);
}
```

It looks like from the documentation that they only support solid border style. That is why the lines are solid but dashed in the other script:
https://html2canvas.hertzen.com/features

It looks like you can have html2canvas add CSS just to their rendered version. Could we do this:
https://github.com/niklasvh/html2canvas/issues/701#issuecomment-149355710

**Comment by Mamaduka** [comment]
@nickhamze reverted code to use html2canvas again. Added minor fix, but sometimes I still get a blue border around image block (when grouped).

Unfortunately, border styling is added via pseudo-elements (`::before`). Since pseudo-elements don't exist in DOM, they cannot be changed via JavaSript. I learned this by trial, error and tons of googling this morning.

**Comment by nickhamze** [comment]
I think I found a workaround. If you put it into spotlight mode I don't get any borders. However there is an opacity issue, didn't know if that was something we could override. 

`.block-editor-block-list__layout .block-editor-block-list__block.is-focus-mode:not(.is-multi-selected) {
    opacity: .5;
    transition: opacity .1s linear;
}`

![core-group-screenshot](https://user-images.githubusercontent.com/158918/73176334-d0952800-40d1-11ea-9542-0dc21586c843.png)

**Comment by Mamaduka** [comment]
@nickhamze 

I get the same result + opacity in the "Spotlight" mode. I can also see block inserters, which are hidden when I click on "Take a BlockShot".
![core-group-screenshot (3)](https://user-images.githubusercontent.com/240569/73179518-01567b00-412d-11ea-8acd-e78e6713d79a.png)

**Comment by nickhamze** [comment]
ok, let's put this one on hold and come back to it later. This is getting frustrating :) .

**Comment by Mamaduka** [comment]
@nickhamze I think I fixed this (with a tiny dirty hack). Try again in a non-"Spotlight" mode.

**Comment by nickhamze** [comment]
Wow, it works. I'll work on the readme but I think it's ready to submit unless you have something else to add. Thanks for not giving up like I did :) .

**Comment by Mamaduka** [comment]
Nothing that comes to my mind right now. We can come back to this issue once a new version of html2canvas is released.
